name: parallel jobs

trigger: none

pool:
  name: linux-selfhosted

stages:
- stage: experiment

  jobs: 
  - job: jobone
    steps:    
    - bash: sleep 45s
    - bash: |
        now=$(date)
        echo 'finishing jobone at: ' $now
  
  - job: jobtwo
    steps: 
    - bash: |
        now=$(date)
        echo 'finishing jobtwo at: ' $now