name: variables basics

trigger: none

variables:
  eval: true
  name: one
  value: initialValue
  group: M365Vars

pool:
  vmImage: "ubuntu-20.04"  

# stages skipped

jobs:
 - job: vars
   displayName: Variable Basics
   steps:

    - script: |
        echo ${{ variables.one }} # outputs initialValue
        echo $(one)
      displayName: First variable pass
    
    - bash: echo '##vso[task.setvariable variable=one]updatedValue'
      displayName: new value one
    
    # compare syntax variants
    - script: |
        echo ${{ variables.one }} # outputs initialValue
      displayName: Template Expression

    - script: |
        echo $(one) # outputs updatedValue
      displayName: Macro Syntax
      
    - script: |
        echo $(M365User)
      displayName: Var from VarGrp